#include<graphics.h>
#include "header.h"


void initializePieces(){
    setcolor(LIGHTGRAY);
    placePieces(TRIANGLE_STARTING,SPACE_VERTICAL);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE/2,SPACE_VERTICAL);
    placePieces(TRIANGLE_ENDING,SPACE_VERTICAL);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE/4,SPACE_VERTICAL+TRIANGLE_HEIGHT/2);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE/2,SPACE_VERTICAL+TRIANGLE_HEIGHT/2);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE*3/4,SPACE_VERTICAL+TRIANGLE_HEIGHT/2);
    for(int i = BOX_STARTING ; i <= BOX_ENDING ; i = i+PLACE_WIDTH)
        placePieces(i,SPACE_VERTICAL+TRIANGLE_HEIGHT);
    for(int i = BOX_STARTING ; i <= BOX_ENDING ; i = i+PLACE_WIDTH)
        placePieces(i,SPACE_VERTICAL+TRIANGLE_HEIGHT+PLACE_WIDTH);

    setcolor(YELLOW);
    placePieces(TRIANGLE_STARTING,SPACE_VERTICAL+TRIANGLE_HEIGHT*2+BOX_LENGTH);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE/2,SPACE_VERTICAL+TRIANGLE_HEIGHT*2+BOX_LENGTH);
    placePieces(TRIANGLE_ENDING,SPACE_VERTICAL+TRIANGLE_HEIGHT*2+BOX_LENGTH);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE/4,SPACE_VERTICAL+TRIANGLE_HEIGHT+BOX_LENGTH+TRIANGLE_HEIGHT/2);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE/2,SPACE_VERTICAL+TRIANGLE_HEIGHT+BOX_LENGTH+TRIANGLE_HEIGHT/2);
    placePieces(TRIANGLE_STARTING+TRIANGLE_BASE*3/4,SPACE_VERTICAL+TRIANGLE_HEIGHT+BOX_LENGTH+TRIANGLE_HEIGHT/2);
    for(int i = BOX_STARTING ; i <= BOX_ENDING ; i = i+PLACE_WIDTH)
        placePieces(i,SPACE_VERTICAL+TRIANGLE_HEIGHT+BOX_LENGTH);
    for(int i = BOX_STARTING ; i <= BOX_ENDING ; i = i+PLACE_WIDTH)
        placePieces(i,SPACE_VERTICAL+TRIANGLE_HEIGHT-PLACE_WIDTH+BOX_LENGTH);

}
